In [5]:
# verify that torch.nn.Conv2D performs the complex conjugate in the correlation

import torch
x = torch.tensor([1+2j, 3+4j])
y = x.conj()
print(f"{x = }")
print(f"{y = }")
print(y.is_conj())   # True  (flag is set)  
z = y.resolve_conj()
print(z.is_conj())   # False  
print(z)             # tensor([1-2j, 3-4j])   

x = tensor([1.+2.j, 3.+4.j])
y = tensor([1.-2.j, 3.-4.j])
True
False
tensor([1.-2.j, 3.-4.j])


In [ ]:
def complex_to_real(inp):
    inp_view_as_complex = torch.view_as_real(inp)
    dim_i = inp_view_as_complex.dim() - 1
    i_r = inp_view_as_complex.select(dim_i, 0)
    i_i = inp_view_as_complex.select(dim_i, 1)
    return (i_r, i_i)

print(complex_to_real(x.resolve_conj()))

(tensor([1., 3.]), tensor([2., 4.]))


In [13]:
# Define the complex tensors
x = torch.tensor([1+2j, 3+4j])
h = torch.tensor([1+1j, 1-1j])

# Perform convolution
result = torch.conv1d(
    x.unsqueeze(0).unsqueeze(0),  # Add batch and channel dimensions
    h.flip(0).unsqueeze(0).unsqueeze(0),  # Flip for convolution and add dimensions
    padding=len(h)-1
)

# Perform convolution
result_noFlip = torch.conv1d(
    x.unsqueeze(0).unsqueeze(0),  # Add batch and channel dimensions
    h.unsqueeze(0).unsqueeze(0),  # Flip for convolution and add dimensions
    padding=len(h)-1
)

# Remove extra dimensions and trim to valid convolution size
print(result)
# result = result.squeeze()[:len(x) + len(h) - 1]
result_noFlip = result_noFlip.squeeze()[:len(x) + len(h) - 1]
print(result)
print(result_noFlip)

tensor([[[-1.+3.j,  2.+8.j,  7.+1.j]]])
tensor([[[-1.+3.j,  2.+8.j,  7.+1.j]]])
tensor([ 3.+1.j,  6.+4.j, -1.+7.j])


In [26]:
import torch.nn.functional as F
y = torch.tensor([[1+2j, 3+4j], [5+6j, 7+8j]])
print(y)
y = y.view(1, 1, 2, 2)
print(y.shape )
y_real = F.interpolate(y.real, scale_factor=2, mode="nearest")
y_imag = F.interpolate(y.imag, scale_factor=2, mode="nearest")
y_upsampled = torch.complex(y_real, y_imag)
y_upsampled

tensor([[1.+2.j, 3.+4.j],
        [5.+6.j, 7.+8.j]])
torch.Size([1, 1, 2, 2])


tensor([[[[1.+2.j, 1.+2.j, 3.+4.j, 3.+4.j],
          [1.+2.j, 1.+2.j, 3.+4.j, 3.+4.j],
          [5.+6.j, 5.+6.j, 7.+8.j, 7.+8.j],
          [5.+6.j, 5.+6.j, 7.+8.j, 7.+8.j]]]])